---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  {{ if eq .KUBE_NAMESPACE .BRANCH_ENV }}
  name: {{ .APP_NAME }}-external-{{ .DRONE_SOURCE_BRANCH }}
  {{ else }}
  name: {{ .APP_NAME }}-external
  {{ end }}
{{ file .INGRESS_EXTERNAL_ANNOTATIONS | indent 2 }}
spec:
  ingressClassName: nginx-external
  tls:
    - hosts:
      {{ if eq .KUBE_NAMESPACE .BRANCH_ENV }}
        - {{ .DRONE_BUILD_NUMBER }}.{{ .BRANCH_ENV }}.homeoffice.gov.uk
        - lcs-{{ .DRONE_SOURCE_BRANCH }}.{{ .BRANCH_ENV }}.homeoffice.gov.uk
      {{ else if eq .KUBE_NAMESPACE .UAT_ENV }}
        - lcs.uat.sas-notprod.homeoffice.gov.uk
      {{ else if eq .KUBE_NAMESPACE .PROD_ENV }}
        - {{ .PRODUCTION_URL }}
      {{ end }}
      {{ if eq .KUBE_NAMESPACE .BRANCH_ENV }}
      secretName: branch-tls-external
      {{ else if eq .KUBE_NAMESPACE .UAT_ENV }}
      secretName: cert-cmio
      {{ else if eq .KUBE_NAMESPACE .PROD_ENV}}
      secretName: cert-cmio-xxq8z
      {{ end }}
  rules:
    {{ if eq .KUBE_NAMESPACE .BRANCH_ENV }}
    - host: lcs-{{ .DRONE_SOURCE_BRANCH }}.{{ .BRANCH_ENV }}.homeoffice.gov.uk
    {{ else if eq .KUBE_NAMESPACE .UAT_ENV }}
    - host: lcs.uat.sas-notprod.homeoffice.gov.uk
    {{ else if eq .KUBE_NAMESPACE .PROD_ENV }}
    - host: {{ .PRODUCTION_URL }}
    {{ end }}
      http:
        paths:
          - path: /
            backend:
              {{ if eq .KUBE_NAMESPACE .BRANCH_ENV }}
              serviceName: {{ .APP_NAME }}-{{ .DRONE_SOURCE_BRANCH }}
              {{ else }}
              serviceName: {{ .APP_NAME }}
              {{ end }}
              servicePort: 10443