apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: branch-tls-internal
  labels:
    cert-manager.io/solver: route53
spec:
  commonName: "*.internal.sas-lcs-branch.homeoffice.gov.uk"
  dnsNames:
  - "*.internal.sas-lcs-branch.homeoffice.gov.uk"
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod
  secretName: branch-tls-internal
