{{ if not (eq .KUBE_NAMESPACE .BRANCH_ENV) }}
labels:
  cert-manager.io/solver: route53
{{ end }}
annotations:
  ingress.kubernetes.io/backend-protocol: "HTTPS"
  ingress.kubernetes.io/force-ssl-redirect: "true"
  {{ if or (eq .KUBE_NAMESPACE .STG_ENV) (eq .KUBE_NAMESPACE .PROD_ENV) }}
  kubernetes.io/ingress.class: "nginx-internal"
  {{ end }}
  {{ if not (eq .KUBE_NAMESPACE .BRANCH_ENV) }}
  cert-manager.io/enabled: "true"
  {{ end }}
