- name: PROXY_SERVICE_HOST
  value: 127.0.0.1
- name: PROXY_SERVICE_PORT
  value: "8080"
- name: ENABLE_UUID_PARAM
  value: "FALSE"
- name: PORT_IN_HOST_HEADER
  value: "FALSE"
- name: VERBOSE_ERROR_PAGES
  value: "TRUE"
- name: EXTRA_NAXSI_RULES
  value: |-
    BasicRule wl:2,1000,1001,1002,1007,1008,1009,1010,1011,1013,1015,1101,1205,1314 "mz:BODY";
    BasicRule wl:0 "mz:$HEADERS_VAR:Cookie";
    BasicRule wl:1500 "mz:FILE_EXT";
- name: ADD_NGINX_SERVER_CFG
  value: |
    add_header Cache-Control private;
    add_header X-Frame-Options "SAMEORIGIN" always;
    add_header X-Content-Type-Options "nosniff" always;
    add_header X-XSS-Protection "1; mode=block" always;
    location /public {
      add_header Cache-Control max-age=86400;
      add_header X-Frame-Options "SAMEORIGIN" always;
      add_header X-Content-Type-Options "nosniff" always;
      add_header X-XSS-Protection "1; mode=block" always;
      alias /public;
    }
